### ISSUE TITLE
NOT mask?

### ISSUE THREAD

**Issue by loudwinston** [nemtsov/json-mask#8]
It'd be nice to have the ability to use json-mask to say what fields should NOT be returned.  For instance, if I have some JSON where every field except one should be included.

Is this possible currently?  I didn't see anything in the API docs for it.

**Comment by nemtsov** [comment]
That would be a great feature to have. I'd love a pull request for it, if you're interested. 

Maybe something that looks like this:

```js
mask({p: {a: 1}, z: 1}, '!p')  // {z: 1}
```

And in case when there are both, the not should take precedence.

**Comment by jordansexton** [comment]
:+1: I've been using this with koa-json-mask and just started using it for body parameter filtering, so I may take a crack at it.

On another note, I've used strong_parameters with Rails, and one thing I found useful was the ability to require parameters and throw an error rather than just permitting/denying them. If this sounds interesting, what kind of syntax do you think might make sense?

**Comment by nemtsov** [comment]
@jordansexton go for it.

Re. throwing errors: I'm not sure I completely understand (perhaps having not used strong_parameters). Do you mean instead of masking values, this lib would be used as a validator to check whether an object matches a certain structure?

**Comment by jordansexton** [comment]
Not instead of masking values, but in addition to. Here are the three behaviors (not mutually exclusive):

```javascript
// existing behavior (inclusion)
> mask({ firstName: 'Foo', lastName: 'Bar' }, 'firstName')
{ firstName: 'Foo' }

// first proposed behavior (exclusion)
> mask({ firstName: 'Foo', lastName: 'Bar' }, '!firstName')
{ lastName: 'Bar' }

> mask({ firstName: 'Foo', lastName: 'Bar' }, '!firstName,!lastName')
{ }

// second proposed behavior (requirement)
> mask({ firstName: 'Foo', lastName: 'Bar' }, 'firstName!')
{ firstName: 'Foo' }

> mask({ firstName: 'Foo', lastName: 'Bar' }, 'firstName!,lastName!,middleName!')
Error: field "middleName" required

// combined behaviors
> mask({ parent: { name: 'Parent', children: [{ name: 'Child' }] } }, 'parent!/!name,children(!name)')
{ parent: { children: [{}] } }

> mask({ parent: { name: 'Parent', children: [{}] } }, 'parent!/!name,children(name!)')
Error: field "parent/children(name)" required
```

This makes sure that the output doesn't have anything you don't want, but also that it definitely has things you do want. What do you think?

**Comment by jordansexton** [comment]
Coming from strong_parameters' [builder-style DSL](/rails/strong_parameters#require-multiple-parameters), the form might be:

```ruby
require(:parent).permit(:children).require(:name)
```

Not only is this less succinct, but it also lacks exclusion, and passing arrays and hashes in is composable, but totally unreadable compared to json-mask. [params](/vesln/params) uses this type of DSL with only/except/require, but doesn't seem to support array or hash values.

**Comment by loudwinston** [comment]
Is doing input validation a use-case for json-mask?  It seems like more of
a library for customizing output, not validating input.

**Comment by jordansexton** [comment]
While it's certainly most commonly used for customizing output (as in koa-json-mask), I would make the argument that customizing (and optionally validating) isn't outside the scope.

1. It doesn't seem like it would take much in terms of technical burden or performance to do accomplish both. Once compiled, this could be memoized (optional; not currently done). It requires adding support for ! before a symbol to the lexer, which is [looked up](/nemtsov/json-mask/blob/master/lib/compiler.js#L44) in a simple hash, adding a flag [around here](/nemtsov/json-mask/blob/master/lib/compiler.js#L89) for the next token, then checking for the flag [in here](/nemtsov/json-mask/blob/master/lib/filter.js#L21).

2. Item 1 would need to be done anyway to support the first proposed !exclusion use case. If the default behavior is whitelisting props, it makes a certain degree of sense to provide for blacklisting. This could be expanded to support the require! use case by peeking at the stack and checking if the ! is before or after the token currently being evaluated.

3. Both are new features that don't break backwards compatibility.

4. It wouldn't be easy to extend json-mask to support the behavior without forking the project, because it requires modifying the compiler, which is efficient but not built for extensibility.

5. There is no node project I could find which currently does this well, and using ! imposes no new complexity for a user of json-mask, as the feature is just an extension to the mask's syntax.

Anyway, all this doesn't mean that this feature definitively falls in json-mask's scope, but to me it suggests there's a niche that could be filled and there are some people trying to do this with other solutions that aren't as powerful or succinct. What's are your thoughts against?

**Comment by loudwinston** [comment]
My thought was that there are other packages that do validation better,
with more options.  For example, https://github.com/Atinux/schema-inspector

Regardless I think this discussion has veered off track from the intended
issue, which was just to add a NOT mask, not to examine the entire scope of
the library :)

**Comment by jordansexton** [comment]
Agreed, I'm not talking about full type validation though. Just simple sanity validation ("Can I expect this deep prop to exist in this object?"). And schema-inspector is so verbose; there's no way to make it anywhere as succinct and expressive as json-mask. I use [square/lgtm](/square/lgtm/wiki#basic-validation) for full validation at the model layer, but it's pretty heavy for the resource layer I use json-mask at.

Anyway, I like your proposed feature.

**Comment by nemtsov** [comment]
@jordansexton apologies for not commenting on this sooner, I was out for the weekend. I agree with @loudwinston, `json-mask` isn't the best library for validation. 

Even if we add the bang `!` to the library that would be just key existence validation; which is only one type. For me, that isn't sufficient. When I validate I want to be thorough, so that anything downstream wouldn't need to re-validate. So, instead of just checking whether a key exists, I tend to check that it isn't empty or null, that it is an integer between 2 and 42 for example or that a key is boolean or a non-empty array. A library I use often for this type of validation is [joi](https://github.com/hapijs/joi). It's designed for validation, and supports all of these use-cases via a fairly succinct api.

But if you're really interested in implementing validation with `json-mask` syntax, let's create a new library that would support:

- json-mask syntax +
- core types: `validate(obj, 'address/city:string, isAdmin:boolean, config:object, friends:array')`
- defined types:  
    - `define('Person', 'name:string, age:number')`
    - `validate(obj, 'person:Person')`
- custom types:
    - `define('EmptyString', function (value) { return '' === value })`
    - `validate(obj, 'name:EmptyString')`
- or / and: `userInput:string|number`, `userInput:string&NotWhitespace`
- optional values: `name:string, age:number?` (name is required, age is optional [strict mode])
- required values: `name:string!, age:number` (name is required, age is optional)

So, I hope you're still interested in implementing the NOT :)

**Comment by jordansexton** [comment]
The value of checking for the existence of properties at the resource layer is not safety and robustness but speed and ease of understanding. json-mask is fast and wouldn't be made appreciably slower by the check, and the syntax is easy to grep.

And, as I said, I was just looking for a property existence check in the syntax of json-mask, not type validation. I strongly prefer to place all type validation in the model layer and not the resource layer, closest to where they may be persisted, and there are libraries that do this asynchronously and with many features already. I have validators for all my models, so I'm not looking to recreate them, or implement them at the HTTP resource layer, as many are necessarily specific to the persistence mechanism (unique and foreign keys if persisted to the DB; file size and name if persisted to the FS) and should be somewhat abstracted away from the language of REST resources which often represent composite objects (Stripe's API is a great example of this).

While blacklisting properties makes some sense to be in scope as a counterpart to whitelisting, I always prefer to whitelist incoming data anyway rather than blacklist. It's safer both in the immediate sense of being strict about what you accept, and also safer for other developers who are working on the project and who may add properties to the model which could then be unknowingly output or allowed to be input at at the resource level.

Because of all this, I don't have much use for the blacklisting feature, so perhaps @loudwinston will come back to it. And perhaps what I'm thinking of isn't really the best use case for json-mask anyway. It was interesting poking around in the compiler, and while I thought it would make sense to do it with similar syntax, I respect your goal of keeping the library's focus tight.

**Comment by vinicius0026** [comment]
Hi guys.
The NOT mask would be very interesting. Is anyone working on it already? I'm asking just to avoid doing duplicate work... I could give it a try if nobody is currently doing it...
Thanks!

**Comment by nemtsov** [comment]
Go for it!

**Comment by anand-bhat** [comment]
:+1:
